/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PrescriptionAnalysis = IDL.Record({
  'dosage' : IDL.Text,
  'confidenceLevel' : IDL.Text,
  'notes' : IDL.Text,
  'frequency' : IDL.Text,
  'medicineName' : IDL.Text,
});
export const ImageAnalysis = IDL.Record({
  'whatToDo' : IDL.Text,
  'possibleCause' : IDL.Text,
  'observation' : IDL.Text,
  'disclaimer' : IDL.Text,
});
export const QueryType = IDL.Variant({
  'symptom' : IDL.Null,
  'prescription' : IDL.Null,
  'advice' : IDL.Null,
});
export const QueryLog = IDL.Record({
  'id' : IDL.Nat,
  'queryType' : QueryType,
  'summary' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const MedicalAdvice = IDL.Record({
  'generalAdvice' : IDL.Text,
  'possibleReasons' : IDL.Text,
  'homeCareTips' : IDL.Vec(IDL.Text),
  'disclaimer' : IDL.Text,
});

export const idlService = IDL.Service({
  'analyzePrescription' : IDL.Func(
      [IDL.Text],
      [PrescriptionAnalysis],
      ['query'],
    ),
  'analyzeSymptomImage' : IDL.Func([IDL.Text], [ImageAnalysis], ['query']),
  'getAllQueries' : IDL.Func([], [IDL.Vec(QueryLog)], ['query']),
  'getMedicalAdvice' : IDL.Func([IDL.Text], [MedicalAdvice], ['query']),
  'getQuery' : IDL.Func([IDL.Nat], [QueryLog], ['query']),
  'getRecentQueries' : IDL.Func([], [IDL.Vec(QueryLog)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PrescriptionAnalysis = IDL.Record({
    'dosage' : IDL.Text,
    'confidenceLevel' : IDL.Text,
    'notes' : IDL.Text,
    'frequency' : IDL.Text,
    'medicineName' : IDL.Text,
  });
  const ImageAnalysis = IDL.Record({
    'whatToDo' : IDL.Text,
    'possibleCause' : IDL.Text,
    'observation' : IDL.Text,
    'disclaimer' : IDL.Text,
  });
  const QueryType = IDL.Variant({
    'symptom' : IDL.Null,
    'prescription' : IDL.Null,
    'advice' : IDL.Null,
  });
  const QueryLog = IDL.Record({
    'id' : IDL.Nat,
    'queryType' : QueryType,
    'summary' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const MedicalAdvice = IDL.Record({
    'generalAdvice' : IDL.Text,
    'possibleReasons' : IDL.Text,
    'homeCareTips' : IDL.Vec(IDL.Text),
    'disclaimer' : IDL.Text,
  });
  
  return IDL.Service({
    'analyzePrescription' : IDL.Func(
        [IDL.Text],
        [PrescriptionAnalysis],
        ['query'],
      ),
    'analyzeSymptomImage' : IDL.Func([IDL.Text], [ImageAnalysis], ['query']),
    'getAllQueries' : IDL.Func([], [IDL.Vec(QueryLog)], ['query']),
    'getMedicalAdvice' : IDL.Func([IDL.Text], [MedicalAdvice], ['query']),
    'getQuery' : IDL.Func([IDL.Nat], [QueryLog], ['query']),
    'getRecentQueries' : IDL.Func([], [IDL.Vec(QueryLog)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };