/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ImageAnalysis {
  'whatToDo' : string,
  'possibleCause' : string,
  'observation' : string,
  'disclaimer' : string,
}
export interface MedicalAdvice {
  'generalAdvice' : string,
  'possibleReasons' : string,
  'homeCareTips' : Array<string>,
  'disclaimer' : string,
}
export interface PrescriptionAnalysis {
  'dosage' : string,
  'confidenceLevel' : string,
  'notes' : string,
  'frequency' : string,
  'medicineName' : string,
}
export interface QueryLog {
  'id' : bigint,
  'queryType' : QueryType,
  'summary' : string,
  'timestamp' : bigint,
}
export type QueryType = { 'symptom' : null } |
  { 'prescription' : null } |
  { 'advice' : null };
export interface UserProfile { 'displayName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'analyzePrescription' : ActorMethod<[string], PrescriptionAnalysis>,
  'analyzeSymptomImage' : ActorMethod<[string], ImageAnalysis>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllQueries' : ActorMethod<[], Array<QueryLog>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMedicalAdvice' : ActorMethod<[string], MedicalAdvice>,
  'getQuery' : ActorMethod<[bigint], QueryLog>,
  'getRecentQueries' : ActorMethod<[], Array<QueryLog>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'greet' : ActorMethod<[string], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];