/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MedicalAdvice {
    generalAdvice: string;
    possibleReasons: string;
    homeCareTips: Array<string>;
    disclaimer: string;
}
export interface QueryLog {
    id: bigint;
    queryType: QueryType;
    summary: string;
    timestamp: bigint;
}
export interface PrescriptionAnalysis {
    dosage: string;
    confidenceLevel: string;
    notes: string;
    frequency: string;
    medicineName: string;
}
export interface ImageAnalysis {
    whatToDo: string;
    possibleCause: string;
    observation: string;
    disclaimer: string;
}
export enum QueryType {
    symptom = "symptom",
    prescription = "prescription",
    advice = "advice"
}
export interface backendInterface {
    analyzePrescription(prescriptionText: string): Promise<PrescriptionAnalysis>;
    analyzeSymptomImage(imageDescription: string): Promise<ImageAnalysis>;
    getAllQueries(): Promise<Array<QueryLog>>;
    getMedicalAdvice(symptoms: string): Promise<MedicalAdvice>;
    getQuery(id: bigint): Promise<QueryLog>;
    getRecentQueries(): Promise<Array<QueryLog>>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
}
import type { QueryLog as _QueryLog, QueryType as _QueryType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async analyzePrescription(arg0: string): Promise<PrescriptionAnalysis> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzePrescription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzePrescription(arg0);
            return result;
        }
    }
    async analyzeSymptomImage(arg0: string): Promise<ImageAnalysis> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeSymptomImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeSymptomImage(arg0);
            return result;
        }
    }
    async getAllQueries(): Promise<Array<QueryLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQueries();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQueries();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMedicalAdvice(arg0: string): Promise<MedicalAdvice> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicalAdvice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicalAdvice(arg0);
            return result;
        }
    }
    async getQuery(arg0: bigint): Promise<QueryLog> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuery(arg0);
                return from_candid_QueryLog_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuery(arg0);
            return from_candid_QueryLog_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentQueries(): Promise<Array<QueryLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentQueries();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentQueries();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _initializeAccessControlWithSecret(_userSecret: string): Promise<void> {
        // no-op stub: access control initialization is handled by the platform
    }
}
function from_candid_QueryLog_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QueryLog): QueryLog {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_QueryType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QueryType): QueryType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    queryType: _QueryType;
    summary: string;
    timestamp: bigint;
}): {
    id: bigint;
    queryType: QueryType;
    summary: string;
    timestamp: bigint;
} {
    return {
        id: value.id,
        queryType: from_candid_QueryType_n4(_uploadFile, _downloadFile, value.queryType),
        summary: value.summary,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    symptom: null;
} | {
    prescription: null;
} | {
    advice: null;
}): QueryType {
    return "symptom" in value ? QueryType.symptom : "prescription" in value ? QueryType.prescription : "advice" in value ? QueryType.advice : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QueryLog>): Array<QueryLog> {
    return value.map((x)=>from_candid_QueryLog_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
